title: Conference Deadlines
description: Countdowns to conference deadlines
author: Abhishek Das

domain: "ahuoguo.github.io"
baseurl: ""

github_username: ahuoguo
github_repo: deadlines

markdown: kramdown
ga_id:

include: ['_pages']
