title: Conference Deadlines
description: Countdowns to conference deadlines
author: ahuoguo
repository: ahuoguo/deadline


domain: "ahuoguo.github.io/deadlines/"
baseurl: ""

github_username: ahuoguo
github_repo: deadlines

markdown: kramdown
ga_id:

include: ['_pages']
